// This file was auto-generated by 'typesafe-i18n'. Any manual changes will be overwritten.
/* eslint-disable */
import type { BaseTranslation as BaseTranslationType, LocalizedString } from 'typesafe-i18n'

export type BaseTranslation = BaseTranslationType
export type BaseLocale = 'en'

export type Locales =
	| 'en'
	| 'ja'

export type Translation = RootTranslation

export type Translations = RootTranslation

type RootTranslation = {
	/**
	 * input time by typing
	 */
	'input time by typing': string
}

export type TranslationFunctions = {
	/**
	 * input time by typing
	 */
	'input time by typing': () => LocalizedString
}

export type Formatters = {}
